package harvester.data;

// Generated Jul 9, 2008 11:14:11 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ContributorContact generated by hbm2java
 */
@Entity
@Table(name = "contributorcontact")
public class ContributorContact implements java.io.Serializable {

	private static final long serialVersionUID = 7280676514562605539L;
	
	private Integer contactid;
	private String name;
	private Contributor contributor;
	private int type;
	private String email;
	private String phone;
	private String jobtitle;
	private int record;
	private int harvest;
	private int failure;
	private int success;
	private int businesstype;
	private String note;

	public static final int BUSINESS_CONTACT = 0;
	public static final int TECHNICAL_CONTACT = 1;
	public static final int FROM_NLA = 0;
	public static final int FROM_OTHER = 1;
	
	//For velocity
	public int BUSINESS_CONTACT() { return BUSINESS_CONTACT; }
	public int TECHNICAL_CONTACT() { return TECHNICAL_CONTACT; }
	public int FROM_NLA() { return FROM_NLA; }
	public int FROM_OTHER () { return FROM_OTHER ; }	

	public ContributorContact() {
	}
	
	public ContributorContact(int businesstype, Integer contactid,
			Contributor contributor, String email, int failure, int harvest,
			String jobtitle, String name, String note, String phone,
			int record, int success, int type) {
		super();
		this.businesstype = businesstype;
		this.contactid = contactid;
		this.contributor = contributor;
		this.email = email;
		this.failure = failure;
		this.harvest = harvest;
		this.jobtitle = jobtitle;
		this.name = name;
		this.note = note;
		this.phone = phone;
		this.record = record;
		this.success = success;
		this.type = type;
	}
	@GenericGenerator(name = "generator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = @Parameter(name = "sequence_name", value = "contributorcontact_seq"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "contactid", nullable = false)
	public Integer getContactid() {
		return this.contactid;
	}

	public void setContactid(Integer contactid) {
		this.contactid = contactid;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contributorid", nullable = false)
	public Contributor getContributor() {
		return contributor;
	}
	public void setContributor(Contributor contributor) {
		this.contributor = contributor;
	}

	@Column(name = "type")
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "jobtitle")
	public String getJobtitle() {
		return this.jobtitle;
	}

	public void setJobtitle(String jobtitle) {
		this.jobtitle = jobtitle;
	}

	@Column(name = "record")
	public int getRecord() {
		return this.record;
	}

	public void setRecord(int record) {
		this.record = record;
	}

	@Column(name = "harvest")
	public int getHarvest() {
		return this.harvest;
	}

	public void setHarvest(int harvest) {
		this.harvest = harvest;
	}

	@Column(name = "failure")
	public int getFailure() {
		return this.failure;
	}

	public void setFailure(int failure) {
		this.failure = failure;
	}

	@Column(name = "success")
	public int getSuccess() {
		return this.success;
	}

	public void setSuccess(int success) {
		this.success = success;
	}

	@Column(name = "businesstype")
	public int getBusinesstype() {
		return this.businesstype;
	}

	public void setBusinesstype(int businesstype) {
		this.businesstype = businesstype;
	}

	@Column(name = "note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
