package harvester.data;

// Generated Jul 9, 2008 11:14:11 AM by Hibernate Tools 3.2.1.GA

import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * HarvestLog generated by hbm2java
 */
@Entity
@Table(name = "harvestlog")
public class HarvestLog implements java.io.Serializable {

	private int harvestlogid;
	private int harvestid;
	private Date timestamp;
	private int errorlevel;
	private String description;
	private Blob recorddata;
	private int hasdata;
	private Step step;
	private String reason;

	public HarvestLog() {
	}

	public static final int INFO = 0;
	public static final int RECORD_ERROR = 1;
	public static final int STEP_ERROR = 2;
	public static final int INIT_ERROR = 3;
	public static final int PROP_INFO = 4;	
	public static final int REPORT_INFO = 5;
	
	public int INFO() { return INFO;}
	public int RECORD_ERROR() { return RECORD_ERROR;}
	public int STEP_ERROR() { return STEP_ERROR;}
	public int INIT_ERROR() { return INIT_ERROR;}
	public int PROP_INFO() { return PROP_INFO;}
	

	public HarvestLog(int harvestid, Date timestamp, int errorlevel,
			String description, Blob recorddata, int hasdata,
			Step step, String reason) {
		this.harvestid = harvestid;
		this.timestamp = timestamp;
		this.errorlevel = errorlevel;
		this.description = description;
		this.recorddata = recorddata;
		this.hasdata = hasdata;
		this.reason = reason;
		this.step = step;
	}
	
	public HarvestLog(int harvestlogid, int harvestid, Date timestamp, int errorlevel,
			String description, int hasdata) {
		this.harvestid = harvestid;
		this.timestamp = timestamp;
		this.errorlevel = errorlevel;
		this.description = description;
		this.harvestlogid = harvestlogid;
		this.hasdata = hasdata;
	}
	

	@GenericGenerator(name = "generator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = @Parameter(name = "sequence_name", value = "harvestlog_seq"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "harvestlogid", nullable = false)
	public int getHarvestlogid() {
		return this.harvestlogid;
	}

	public void setHarvestlogid(int harvestlogid) {
		this.harvestlogid = harvestlogid;
	}

	@Column(name = "harvestid")
	public int getHarvestid() {
		return this.harvestid;
	}

	public void setHarvestid(int harvestid) {
		this.harvestid = harvestid;
	}

	@Column(name = "timestamp")
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "errorlevel")
	public int getErrorlevel() {
		return this.errorlevel;
	}

	public void setErrorlevel(int errorlevel) {
		this.errorlevel = errorlevel;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "recorddata")
	public Blob getRecorddata() {
		return this.recorddata;
	}

	public void setRecorddata(Blob recorddata) {
		this.recorddata = recorddata;
	}

	@Column(name = "hasdata")
	public int getHasdata() {
		return this.hasdata;
	}

	public void setHasdata(int hasdata) {
		this.hasdata = hasdata;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stepid")
	public Step getStep() {
		return step;
	}
	public void setStep(Step step) {
		this.step = step;
	}
	
	@Column(name = "reason")
	public String getReason() {
		return reason;
	}
	public void setReason(String reason) {
		this.reason = reason;
	}

}
