package harvester.data;

// Generated Jul 9, 2008 11:14:11 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Harvest generated by hbm2java
 */
@Entity
@Table(name = "harvest")
public class Harvest implements java.io.Serializable {

	private int harvestid;
	private Set<HarvestLog> harvestlogs = new HashSet<HarvestLog>(0);
	private Set<HarvestData> harvestdata = new HashSet<HarvestData>(0);
	private Contributor contributor;
	private Integer profileid;
	private String status;
	private int statuscode;
	private int recordscompleted;
	private int totalrecords;
	private int deletionsread;
	private int deletionsperformed;
	private int recordsadded;
	private Date starttime;
	private String harvestfrom;
	private String harvestuntil;	
	
	private Date endtime;
	private int type;

	public static final int SUCCESSFUL = 0;
	public static final int RUNNING = 1;
	public static final int FAILED = 2;

	public int SUCCESSFUL() {
		return SUCCESSFUL;
	}
	public int RUNNING() {
		return RUNNING;
	}
	public int FAILED() {
		return FAILED;
	}
	
	public Harvest() {
	}

	public Harvest(Set<HarvestLog> harvestlogs, Set<HarvestData> harvestdata,
			Contributor contributor, Integer profileid, String status,
			int statuscode, int recordscompleted, int recordsadded, int totalrecords, int deletionsread, int deletionsperformed,
			Date starttime, String harvestfrom, String harvestuntil, Date endtime, int type) {
		this.harvestlogs = harvestlogs;
		this.harvestdata = harvestdata;
		this.contributor = contributor;
		this.profileid = profileid;
		this.status = status;
		this.statuscode = statuscode;
		this.recordscompleted = recordscompleted;
		this.totalrecords = totalrecords;
		this.recordsadded = recordsadded;
		this.starttime = starttime;
		this.harvestfrom = harvestfrom;
		this.endtime = endtime;
		this.type = type;
		this.harvestuntil = harvestuntil;
		
		this.deletionsperformed = deletionsperformed;
		this.deletionsread = deletionsread;
	}

	@GenericGenerator(name = "generator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = @Parameter(name = "sequence_name", value = "harvest_seq"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "harvestid", nullable = false)
	public int getHarvestid() {
		return this.harvestid;
	}

	public void setHarvestid(int harvestid) {
		this.harvestid = harvestid;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "harvestid", updatable = false)
	@OrderBy("harvestlogid ASC")
	public Set<HarvestLog> getHarvestlogs() {
		return this.harvestlogs;
	}

	public void setHarvestlogs(Set<HarvestLog> harvestlogs) {
		this.harvestlogs = harvestlogs;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "harvestid", updatable = false)
	//@Cascade( { CascadeType.DELETE_ORPHAN })
	@OrderBy("harvestdataid ASC")
	public Set<HarvestData> getHarvestdata() {
		return this.harvestdata;
	}

	public void setHarvestdata(Set<HarvestData> harvestdata) {
		this.harvestdata = harvestdata;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contributorid")
	public Contributor getContributor() {
		return this.contributor;
	}

	public void setContributor(Contributor contributor) {
		this.contributor = contributor;
	}

	@Column(name = "profileid")
	public Integer getProfileid() {
		return this.profileid;
	}

	public void setProfileid(Integer profileid) {
		this.profileid = profileid;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "statuscode")
	public int getStatuscode() {
		return this.statuscode;
	}

	public void setStatuscode(int statuscode) {
		this.statuscode = statuscode;
	}

	@Column(name = "recordscompleted")
	public int getRecordscompleted() {
		return this.recordscompleted;
	}

	public void setRecordscompleted(int recordscompleted) {
		this.recordscompleted = recordscompleted;
	}

	@Column(name = "totalrecords")
	public int getTotalrecords() {
		return this.totalrecords;
	}

	public void setTotalrecords(int totalrecords) {
		this.totalrecords = totalrecords;
	}

	@Column(name = "starttime")
	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	@Column(name = "harvestfrom")
	public String getHarvestfrom() {
		return this.harvestfrom;
	}

	public void setHarvestfrom(String harvestfrom) {
		this.harvestfrom = harvestfrom;
	}

	@Column(name = "endtime")
	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	@Column(name = "type")
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}
	
	@Column(name = "harvestuntil")
	public String getHarvestuntil() {
		return harvestuntil;
	}	
	public void setHarvestuntil(String harvestuntil) {
		this.harvestuntil = harvestuntil;
	}
	
	@Column(name = "deletionsread")
	public int getDeletionsread() {
		return deletionsread;
	}
	public void setDeletionsread(int deletionsread) {
		this.deletionsread = deletionsread;
	}
	
	@Column(name = "deletionsperformed")
	public int getDeletionsperformed() {
		return deletionsperformed;
	}
	public void setDeletionsperformed(int deletionsperformed) {
		this.deletionsperformed = deletionsperformed;
	}
	
	@Column(name="recordsadded")
	public int getRecordsadded() {
		return recordsadded;
	}
	public void setRecordsadded(int recordsadded) {
		this.recordsadded = recordsadded;
	}
	
}
