package harvester.data;

// Generated Jul 9, 2008 11:14:11 AM by Hibernate Tools 3.2.1.GA

import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * HarvestData generated by hbm2java
 */
@Entity
@Table(name = "harvestdata")
public class HarvestData implements java.io.Serializable {

	private int harvestdataid;
	private int harvestid;
	private int stage;
	private Blob data;

	public HarvestData() {
	}

//	public HarvestData(Harvest harvest) {
//		this.harvest = harvest;
//	}

	public HarvestData(int harvestid, int stage, Blob data) {
		this.harvestid = harvestid;
		this.stage = stage;
		this.data = data;
	}

	@GenericGenerator(name = "generator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = @Parameter(name = "sequence_name", value = "harvestdata_seq"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "harvestdataid", nullable = false)
	public int getHarvestdataid() {
		return this.harvestdataid;
	}

	public void setHarvestdataid(int harvestdataid) {
		this.harvestdataid = harvestdataid;
	}

	@Column(name = "harvestid")
	public int getHarvestid() {
		return this.harvestid;
	}

	public void setHarvestid(int harvestid) {
		this.harvestid = harvestid;
	}

	@Column(name = "stage")
	public int getStage() {
		return this.stage;
	}

	public void setStage(int stage) {
		this.stage = stage;
	}

	@Column(name = "data")
	public Blob getData() {
		return this.data;
	}

	public void setData(Blob data) {
		this.data = data;
	}

}
