package harvester.data;

// Generated Jul 9, 2008 11:14:11 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Note generated by hbm2java
 */
@Entity
@Table(name = "note")
public class Note implements java.io.Serializable {

	private Integer noteid;
	private int contributorid;
	private Date timestamp;
	private String creator;
	private String description;

	public Note() {
	}

	public Note(int contributorid, Date timestamp, String creator,
			String description) {
		this.contributorid = contributorid;
		this.timestamp = timestamp;
		this.creator = creator;
		this.description = description;
	}

	@GenericGenerator(name = "generator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = @Parameter(name = "sequence_name", value = "note_seq"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "noteid", nullable = false)
	public Integer getNoteid() {
		return this.noteid;
	}

	public void setNoteid(Integer noteid) {
		this.noteid = noteid;
	}

	@Column(name = "contributorid")
	public int getContributorid() {
		return this.contributorid;
	}

	public void setContributorid(int contributorid) {
		this.contributorid = contributorid;
	}

	@Column(name = "timestamp")
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "creator")
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
