package harvester.data;

// Generated Jul 9, 2008 11:14:11 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ParameterOption generated by hbm2java
 */
@Entity
@Table(name = "parameteroption")
public class ParameterOption implements java.io.Serializable {

	private static final long serialVersionUID = 7908459805537747360L;
	
	private Integer poid;
	private Integer piid;
	private String value;
	private String description;

	public ParameterOption() {
	}

	//an alternative primary key for this table is (piid, vkey)
	//auto generated parameteroption equals/hashCode code follows
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((piid == null) ? 0 : piid.hashCode());
		result = prime * result + ((value == null) ? 0 : value.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final ParameterOption other = (ParameterOption) obj;
		if (piid == null) {
			if (other.piid != null)
				return false;
		} else if (!piid.equals(other.piid))
			return false;
		if (value == null) {
			if (other.value != null)
				return false;
		} else if (!value.equals(other.value))
			return false;
		return true;
	}

	public ParameterOption(Integer piid, String value, String description) {
		this.piid = piid;
		this.value = value;
		this.description = description;
	}

	@GenericGenerator(name = "generator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = @Parameter(name = "sequence_name", value = "parameteroption_seq"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "poid", nullable = false)
	public Integer getPoid() {
		return this.poid;
	}

	public void setPoid(Integer poid) {
		this.poid = poid;
	}

	@Column(name = "piid")
	public Integer getPiid() {
		return this.piid;
	}

	public void setPiid(Integer piid) {
		this.piid = piid;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
