package harvester.data;

// Generated Jul 9, 2008 11:14:11 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ParameterInformation generated by hbm2java
 */
@Entity
@Table(name = "parameterinformation")
public class ParameterInformation implements java.io.Serializable {

	private static final long serialVersionUID = -3107417660344944715L;
	
	private Integer piid;
	private Step step;
	private Set<ParameterOption> options = new HashSet<ParameterOption>(0);
	private Set<ParameterInformation> nested = new HashSet<ParameterInformation>(0);
	private Integer parentpiid;
	private String parametername;
	private String defaultvalue;
	private String type;
	private String description;
	private int editibility;

	//for editibility
	public static int NORMAL = 0;
	public static int REQUIRED = 1;
	public static int READ_ONLY = 2;
	public static int HIDE = 3;
	
	
	public ParameterInformation() {
	}

	public boolean equals(Object obj)
	{
		if(this == obj)
			return true;
		if((obj == null) || (obj.getClass() != this.getClass()))
			return false;
		ParameterInformation pi = (ParameterInformation) obj;	
		return (this.getPiid().equals(pi.getPiid()));	//since we never create these, they could always have a valid piid
		//if(step.getStepid() == pi.getStep().getStepid() && parametername.equals(pi.getParametername()))
		//	return true;
		//return false;
	}
	
	public int hashCode()
	{
		int result = 7;
		if(piid != null)
			result = 17*result + piid;
		if(parametername != null)
			result = 29*result + parametername.hashCode();
		if(step != null)
			result = 31*result + step.getStepid();
		return result;
	}

	public ParameterInformation(Step step) {
		this.step = step;
	}

	public ParameterInformation(Step step, Set<ParameterOption> options,
			Set<ParameterInformation> nested, Integer parentpiid,
			String parametername, String defaultvalue, String type,
			String description, int editibility) {
		this.step = step;
		this.options = options;
		this.nested = nested;
		this.parentpiid = parentpiid;
		this.parametername = parametername;
		this.defaultvalue = defaultvalue;
		this.type = type;
		this.description = description;
		this.editibility = editibility;
	}

	@GenericGenerator(name = "generator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = @Parameter(name = "sequence_name", value = "parameterinformation_seq"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "piid", nullable = false)
	public Integer getPiid() {
		return this.piid;
	}

	public void setPiid(Integer piid) {
		this.piid = piid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stepid", nullable = false)
	public Step getStep() {
		return this.step;
	}

	public void setStep(Step step) {
		this.step = step;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "piid", updatable = false)
	@OrderBy("poid ASC")
	public Set<ParameterOption> getOptions() {
		return this.options;
	}

	public void setOptions(Set<ParameterOption> options) {
		this.options = options;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "parentpiid", updatable = false)
	@OrderBy("piid ASC")
	public Set<ParameterInformation> getNested() {
		return this.nested;
	}

	public void setNested(Set<ParameterInformation> nested) {
		this.nested = nested;
	}

	@Column(name = "parentpiid")
	public Integer getParentpiid() {
		return this.parentpiid;
	}

	public void setParentpiid(Integer parentpiid) {
		this.parentpiid = parentpiid;
	}

	@Column(name = "parametername")
	public String getParametername() {
		return this.parametername;
	}

	public void setParametername(String parametername) {
		this.parametername = parametername;
	}

	@Column(name = "defaultvalue")
	public String getDefaultvalue() {
		return this.defaultvalue;
	}

	public void setDefaultvalue(String defaultvalue) {
		this.defaultvalue = defaultvalue;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "editibility")
	public int getEditibility() {
		return this.editibility;
	}

	public void setEditibility(int editibility) {
		this.editibility = editibility;
	}

}
