package harvester.data;

// Generated Jul 9, 2008 11:14:11 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile")
public class Profile implements java.io.Serializable {

	private static final long serialVersionUID = 7175811556170701248L;
	
	private Integer profileid;
	private String name;
	private String description;
	private int type;
	private Set<ProfileStep> profilesteps = new HashSet<ProfileStep>(0);

	public Profile() {
	}

	//these correspond to the type field above
	public static final int OAI = 0;
	public static final int Z3950 = 1;
	
	public int OAI() { return OAI;}
	public int Z3950() { return Z3950;}
	
	//Used by the processor for identifying profiles
	public static final int TEST_PROFILE = 0;
	public static final int PRODUCTION_PROFILE = 1;
	
	public String toString() {
		return "profileid = " + profileid + " name=" + name + " description=" + description;
	}
	
	public Object clone()
	{
		try
		{
			Profile dp = new Profile();
			dp.setProfileid(this.getProfileid());
			dp.setName(this.getName());
			dp.setDescription(this.getDescription());
			dp.setType(this.getType());
			for(ProfileStep ps : this.getProfilesteps())
				dp.getProfilesteps().add((ProfileStep)ps.clone());
			return dp;
		}
		catch ( Exception e )
		{
			return null;
		}
	}

	public Profile(String name, String description, int type,
			Set<ProfileStep> profilesteps) {
		this.name = name;
		this.description = description;
		this.type = type;
		this.profilesteps = profilesteps;
	}

	@GenericGenerator(name = "generator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = @Parameter(name = "sequence_name", value = "profile_seq"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "profileid", nullable = false)
	public Integer getProfileid() {
		return this.profileid;
	}

	public void setProfileid(Integer profileid) {
		this.profileid = profileid;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type")
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "profileid")
	@Cascade( { CascadeType.ALL, CascadeType.DELETE_ORPHAN })
	@OrderBy("position ASC")
	public Set<ProfileStep> getProfilesteps() {
		return this.profilesteps;
	}

	public void setProfilesteps(Set<ProfileStep> profilesteps) {
		this.profilesteps = profilesteps;
	}

}
