package harvester.data;

// Generated Jul 9, 2008 11:14:11 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Step generated by hbm2java
 */
@Entity
@Table(name = "step")
public class Step implements java.io.Serializable {

	private int stepid;
	private String classname;
	private String name;
	private String inputtype;
	private String outputtype;
	private int type;
	private String description;
	private Set<ParameterInformation> pis = new HashSet<ParameterInformation>(0);

	public Step() {
	}

	public static final int INPUT = 0;
	public static final int OUTPUT = 1;
	public static final int VALIDATOR = 2;
	public static final int TRANSLATOR = 3;
	
	public int INPUT() { return INPUT;}
	public int OUTPUT() { return OUTPUT;}
	public int VALIDATOR() { return VALIDATOR;}
	public int TRANSLATOR() { return TRANSLATOR;}
	
	public Step(String classname, String name, String inputtype,
			String outputtype, int type, String description,
			Set<ParameterInformation> pis) {
		this.classname = classname;
		this.name = name;
		this.inputtype = inputtype;
		this.outputtype = outputtype;
		this.type = type;
		this.description = description;
		this.pis = pis;
	}

	public void addParameterinfo(ParameterInformation pi)
	{
		pi.setStep(this);
		pis.add(pi);
	}
	
	public boolean equals(Object obj)
	{
		if(this == obj)
			return true;
		if((obj == null) || (obj.getClass() != this.getClass()))
			return false;
		Step s = (Step) obj;
		if(s.getStepid() == stepid)
			return true;
		return false;
	}
	
	public int hashCode()
	{
		return stepid;
	}

	@GenericGenerator(name = "generator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = @Parameter(name = "sequence_name", value = "step_seq"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "stepid", nullable = false)
	public int getStepid() {
		return this.stepid;
	}

	public void setStepid(int stepid) {
		this.stepid = stepid;
	}

	@Column(name = "classname")
	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "inputtype")
	public String getInputtype() {
		return this.inputtype;
	}

	public void setInputtype(String inputtype) {
		this.inputtype = inputtype;
	}

	@Column(name = "outputtype")
	public String getOutputtype() {
		return this.outputtype;
	}

	public void setOutputtype(String outputtype) {
		this.outputtype = outputtype;
	}

	@Column(name = "type")
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "step")
	@OrderBy("piid ASC")
	public Set<ParameterInformation> getPis() {
		return this.pis;
	}

	public void setPis(Set<ParameterInformation> pis) {
		this.pis = pis;
	}

}
