#!/bin/bash
cd ..
echo NOTE! Tests are not being run, please run them seperately if you need to

mvn -Dmaven.test.skip=true package
if [ "$?" -ne 0 ]; then
  echo "Build failed"
  exit 1
fi

cd scripts
echo -----------------COMPILING COMPLETE
echo deleting current deployment folder
rm -rf ../deployment
echo copying to ../deployment folder
mkdir ../deployment
mkdir ../deployment/HarvesterClient
mkdir ../deployment/HarvesterProcessor
mkdir ../deployment/Scheduler
rsync -r --exclude=.svn ../HarvesterClient/target/HarvesterClient/* ../deployment/HarvesterClient/
rsync -r --exclude=.svn ../HarvesterProcessor/target/HarvesterProcessor/* ../deployment/HarvesterProcessor/
rsync -r --exclude=.svn ../Scheduler/target/Scheduler/* ../deployment/Scheduler/

echo ---------------FINISHED COPYING
